# Generated by Django 5.0.7 on 2024-08-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("roll", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.TextField()),
            ],
        ),
    ]
